---
 - hosts: cstudio
   remote_user: root
   become_user: yes
   vars_files:
    - ../std_vars.yaml
   tasks:
    - name: create mysql user
      user:
       name: mysql
       state: present
       uid: "{{mysql_user_uid}}"

    - name: create and config /etc/my.cnf
      template:
       src: template/{{ mysql_mycnf }}
       dest: /etc/my.cnf
       owner: mysql
       group: mysql
       backup: yes

    - name: install mysql to /usr/local/mysql
      import_tasks: common/install_mysql.yaml

    - name: init mysql datadir
      import_tasks: common/initialize_mysql_datadir.yaml

    - name: create libmysqlclient_r.so file for php-5.6
      when: mtls_with_php == "yes"
      file:
       src: {{mysql_base_dir}}/lib/libmysqlclient.so
       dest: {{mysql_base_dir}}/lib/libmysqlclient_r.so
       state: link
       owner: mysql
       group: mysql

    - name: config systemd
      import_tasks: common/config_mysql_systemd.yaml
      when: ansible_distribution_major_version == "7"

    - name: start mysql
      shell: systemctl start mysql
      when: ansible_distribution_major_version == "7"
...