---
 - hosts: cstudio
   remote_user: root
   become_user: yes
   vars:
    backup_suffix: '20171025'
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: 备份连接文件
      shell: mv {{ mysql_base_dir | replace('mysql/','mysql') }} {{mysql_base_dir | replace('mysql/','mysql') + '.backup.'+backup_suffix}}

    - name: 解压安装包到/usr/local/
      unarchive:
       src: "{{ mysql_packages_dir + mysql_package}}"
       dest: "{{ mysql_base_dir | replace('mysql/','') }}"
       owner: "{{mysql_user}}"
       group: "{{mysql_group}}"

    - name: 创建连接到新版mysql的连接文件
      file:
       src: "{{ mysql_base_dir | replace('mysql/','/') + (mysql_package | replace('.tar.gz',''))}}"
       dest: "{{ mysql_base_dir | replace('mysql/','mysql')}}"
       owner: "{{mysql_user}}"
       group: "{{mysql_group}}"
       state: link
       
       
    