---
 - hosts: uwsgiweb
   remote_user: root
   become_user: yes
   vars_files:
    - ../../../config.yaml

   tasks:
    - name: install dependents
      import_tasks: common/install_python_dependents.yaml

    - name: install python
      import_tasks: common/install_python.yaml

    - name: install mysqlclient
      import_tasks: common/install_mysqlclient.yaml

    - name: install django
      import_tasks: common/install_django.yaml

    - name: install uwsgi
      import_tasks: common/install_uwsgi.yaml

    - name: install bs4
      import_tasks: common/install_bs4.yaml

    - name: install requests
      import_tasks: common/install_requests.yaml

    


    
      
       

      
