---
 - hosts: zabbixstudio
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: install dependents
      import_tasks: common/install_dependents.yaml

    - name: stop httpd.service
      when: ansible_distribution_major_version == "7"
      systemd:
       name: httpd
       state: stopped
       daemon_reload: yes
       
    - name: install php
      import_tasks: common/install_php.yaml

    - name: config httpd
      copy:
       src: template/httpd.conf
       dest: /usr/local/httpd/conf/httpd.conf

    - name: start httpd.service
      when: ansible_distribution_major_version == "7"
      systemd:
       name: httpd
       state: started
       daemon_reload: yes
