---
 - hosts: cstudio
   remote_user: root
   become_user: yes
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: add zabbix user to system
      user:
       name: zabbix
       state: present

    - name: remove /usr/local/httpd/htdocs/index.html
      file:
       dest: /usr/local/httpd/htdocs/index.html
       state: absent 

    - import_tasks: common/install_dependents.yaml

    - import_tasks: common/install_server_node.yaml
      
    - name: stop httpd(linux-6)
      when: ansible_distribution_major_version == "6"
      service:
       name: httpd
       state: started

    - name: stop httpd(linux-7)
      when: ansible_distribution_major_version == "7"
      systemd:
       name: httpd
       state: started

    - name: config service
      import_tasks: ./common/config_service.yaml

#    - name: start zabbix-server
#      shell: /usr/local/zabbix/sbin/zabbix_server 
#    
#    - name: start zabbix-agent(on zabbix-server host)
#      shell: /usr/local/zabbix/sbin/zabbix_agentd