---
 - name: stransfer sql to remote host
   template: 
    src: ../template/master_slaves.j2
    dest: /tmp/master_slaves.sql

 - name: create replication user on master / start slave on slave
   when:
   shell: mysql -hlocalhost -S /tmp/mysql.sock < /tmp/master_slaves.sql
