---
#由本地传输mysql安装包到目标主机、并把安装包解压到/usr/local/目录
#等价bash
#scp mysql-xxxx.tar.gz 192.168.xx.xx:/tmp/
#tar -xvf /tmp/mysq-xxxx.tar.gz -C /usr/local/
 - name: transfer mysql install package to remote host and unarchive to /usr/local/
   unarchive:
    src: "{{ mysql_install_package_local_path }}/{{ mysql_install_package }}"
    dest: /usr/local/
    owner: mysql
    group: mysql

#设置权限
#等价bash
#chown -R mysql:mysql /usr/local/mysql-xxxx
 - name: change owner to mysql user
   file:
    path: /usr/local/{{ mysql_install_package | regex_replace('.tar.gz','') }}
    owner: mysql
    group: mysql
    recurse: yes

#创建连接文件
#等价bash
#ln -s /usr/local/mysql-xxxx /usr/local/mysql
 - name: make link /usr/local/mysql-xx.yy.zz to /usr/local/mysql
   file:
    src: /usr/local/{{ mysql_install_package | regex_replace('.tar.gz','') }}
    dest: /usr/local/mysql
    state: link
    owner: mysql
    group: mysql


