---
 - hosts: centos65
   remote_user: root
   become_user: yes
   vars_files:
    - ../../../config.yaml
    - vars/var_mycat.yaml 

   tasks:
    - name: install dependents
      import_tasks: common/install_dependents.yaml
      
    - name: install mycat
      import_tasks: common/install_mycat.yaml
