---
- hosts: actionsky

  tasks:
    - name: ping target hosts
      ping:

    - name: install vim 
      yum:
        name: vim
        state: present

    - name: install less
      yum:
        name: less
        state: present

    - name: install which
      yum:
        name: which
        state: present

    - name: install wget
      yum:
        name: wget
        state: present

    - name: install net-tools
      yum:
        name: net-tools
        state: present

    - name: install fontconfig
      yum:
        name: fontconfig
        state: present

    - name: install libaio
      yum:
        name: libaio
        state: present

    - name: install hwloc
      yum:
        name: hwloc
        state: present

    - name: install libpciaccess
      yum: 
        name: libpciaccess
        state: present

    - name: install lsof 
      yum:
        name: lsof 
        state: present 

...
